version: "3.9"

services:
  mysql:
    image: mysql:5.7
    container_name: db_mysql
    volumes:
      - pokemon_db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db_pokemon
    networks:
      - pokemon_api_network
  app:
    container_name: app
    build:
      context: .
    ports:
      - 8080:8080
    depends_on:
      - mysql
    environment:
      DB_USERNAME: user
      DB_PASSWORD: 123
      DB_ADDRESS: mysql
      DB_PORT: 3306
      DB_DBNAME: db_pokemon
    networks:
      - pokemon_api_network

volumes:
  pokemon_db:

networks:
  pokemon_api_network:
    name: pokemon_api_network
    driver: bridge