apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokemon-api
  labels:
    name: pokemon-api
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pokemon-api
  template:
    metadata:
      labels:
        name: pokemon-api
    spec:
      containers:
      - name: pokemon-api
        image: winarto007/pokemon-api:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: pokemon-api-service
spec:
  type: LoadBalancer
  selector:
    name: pokemon-api
  ports:
    - port: 8080
      targetPort: 8080

---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-pokemon-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pokemon-api
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target: 
          type: Utilization
          averageUtilization: 50

